### PR TITLE
Updated API to support composing Table Valued Functions

### LINKED ISSUE #1: Table valued functions are not composable
Attempting to call a TVF from within a LINQ query results in an exception:

```
System.NotSupportedException: The specified method 
'System.Linq.IQueryable`1[EntityFramework.Functions.Tests.Examples.ContactInformation] ufnGetContactInformation(System.Nullable`1[System.Int32])' 
on the type 'EntityFramework.Functions.Tests.Examples.AdventureWorks' cannot 
be translated into a LINQ to Entities store expression because its return 
type does not match the return type of the function specified by its DbFunction attribute.

    at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.FunctionCallTranslator.ValidateReturnType(DbExpression result, TypeUsage actualReturnType, ExpressionConverter parent, MethodCallExpression call, Type clrReturnType, Boolean isElementOfCollection)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.FunctionCallTranslator.ValidateReturnType(DbExpression result, TypeUsage actualReturnType, ExpressionConverter parent, MethodCallExpression call, Type clrReturnType, Boolean isElementOfCollection)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.FunctionCallTranslator.TranslateFunctionCall(ExpressionConverter parent, MethodCallExpression call, DbFunctionAttribute functionAttribute)

```

The problem is that `FunctionCallTranslator.TranslateFunctionCall` looks up the function using the `DbFunctionAttribute.NamespaceName` property to get the namespace, but since the namespace is set to `"CodeFirstDatabaseSchema"` rather than the entity container name the function can't be found in CSpace and it gets looked up in SSpace instead (in `Perspective.TryGetFunctionByName`). The SSpace version of the function has the wrong return type, so `FunctionCallTranslator.ValidateReturnType` fails.

One fix is to change the constructor for `EntityFramework.Functions.FunctionAttribute` to something like 
```
       public FunctionAttribute(FunctionType type, string name, string namespaceName = Function.CodeFirstDatabaseSchema)
            : base(namespaceName, name) 
```
and add documentation that the `namespaceName` parameter should only be set for TVF imports. That's a little smelly though. I've put together a small change that adds specific attributes for each `FunctionType` to make things a little more clear. I'll submit a pull request for that, but maybe you can figure out away to make everything work correctly without adding anything to the API. I did some experimentation in `Function.AddFunction` but I couldn't figure out anything that worked.

### PR DESCRIPTION
**Pull request by SteveRuble**
Modified FunctionAttribute to optionally accept `namespaceName`
parameter which must be set for composed calls to Table Valued Functions
to work. Added attributes derived from FunctionAttribute which take the
necessary parameters for each `FunctionType` to clarify what is required
for each type of function. This resolves #1, although it may not be the best resolution.

### CODE REVIEW

**Comment by Dixin** [comment]
Thank you very much. But the unit tests fail?

image

**Comment by SteveRuble** [comment]
My initial commit was broken, but I fixed it in commit 54c4ae9. I thought that subsequent commits I made to the same branch in my fork would be included in the pull request, but maybe I misunderstood. Should I do another pull request?

**Comment by Dixin** [comment]
Updated nuget package, and added your name to the package description.

**Comment by skurik** [comment]
@SteveRuble I think this PR makes it impossible to use built-in TVFs (like `STRING_SPLIT`) with code-first.

I have 

```csharp
[ComplexType]
public class StringSplitValue
{
    public string Value { get; set; }
}

public abstract class DbContext : System.Data.Entity.DbContext
{
    [TableValuedFunction(name: nameof(String_Split), dbContextName: "CodeFirstDatabaseSchema")]
    public IQueryable<StringSplitValue> String_Split(string @string, string separator)
    {
        var sourceParameter = new ObjectParameter("Source", @string);
        var separatorParameter = new ObjectParameter("Separator", separator);

        return ObjectContext.CreateQuery<StringSplitValue>($"STRING_SPLIT(@Source, @Separator)", sourceParameter, separatorParameter);
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Conventions.Add(new FunctionConvention<DbContext>());
        modelBuilder.AddComplexTypesFromAssembly(typeof(DbContext).Assembly);
    }
}
```

and the `FunctionAttribute` constructor is throwing

```
The namespaceName parameter must be set for Table Valued Functions.
```

But I can't use anything else than __CodeFirstDatabaseSchema__, it's the hard-coded namespace value for code-first...

**Comment by SteveRuble** [comment]
@skurik You could be right, but I am not going to be able to help you with this, sorry. I haven't even used EF since 2018.

**Pull request merged**
